version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    deploy:
      resources:
        limits:
          memory: ${MEILSEARCH_MEMORY_LIMITS}
    hostname: meilisearch
    container_name: meilisearch
    user: ${USER_UID}:${USER_UID}
    #restart: unless-stopped
    #command: ./meilisearch --master-key=${MEILISEARCH_KEY} --no-analytics
    command: ./meilisearch --no-analytics --http-payload-size-limit=500Mb
    ports:
      - "127.0.0.1:${MEILISEARCH_PORT}:${MEILISEARCH_PORT}"
    volumes:
      - ${MEILISEARCH_DATA}:/data.ms
    networks:
      - intranet
