name: "pre-release"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "pre-release"
          prerelease: true
          title: "Pre-Stage Build"
